title: Kylan DoRian
description: DevOps Administrator of JK-acme.
social_link: mstdn.plus
social_username: jokerian
github_repo: page
github_username: jokerian
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
